// src/app/layout.server.tsx (یک کامپوننت سروری)
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};